nodeLinker: "pnp"
yarnPath: ".yarn/releases/yarn-3.1.1.cjs"
packageExtensions:
  jest-config@*:
    dependencies:
      jest-runtime: "*"
  jest-cli@*:
    dependencies:
      "@jest/reporters": "*"
      "@jest/console": "*"